version: '3'
services:
  web:
    build: .
    command: shotgun config.ru --host '0.0.0.0' --port 5000
    entrypoint: ["./scripts/wait-for-it.sh", "db:5432" , "--", "./scripts/after_hook.sh"]
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db/grape_task
  db:
    image: healthcheck/postgres:alpine