development:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: 'postgresql'
  encoding: 'utf-8'
  database: 'grape_task'
  user: 'postgres'

# test:
#   host: 'db-test'
#   adapter: 'postgresql'
#   encoding: 'utf-8'
#   database: 'grape_task'
#   user: 'postgres'  